# Site settings
title: Travel With Anna
email: annacharbonneauphd@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am currently on a year long adventure around the world. I have a PhD 
  in clinical psychology. In 2014, I left my regular job as a health psychologist
  to travel full time. This is about travel adventure, exploring new cultures,
  psychology, and my new task of learning web development. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

github_username:  AMCharbonneau

# Build settings
markdown: kramdown

paginate: 4
paginate_path: "/postlist/blog/page:num"

defaults:
  -
    scope:
      path: ""
    values:
      author: "Anna Charbonneau"

