# Site settings
title: Travel With Anna
email: annacharbonneauphd@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Psychologist, web developer, nomad.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

github_username:  AMCharbonneau

# Build settings
markdown: kramdown

paginate: 4
paginate_path: "/postlist/blog/page:num" 

defaults:
  -
    scope:
      path: ""
    values:
      author: "Anna Charbonneau"

